apiVersion: v1
kind: ConfigMap
metadata:
  name: erp-template-config
  namespace: erp-template
  labels:
    app.kubernetes.io/name: erp-template
data:
  NODE_ENV: "production"
  DEMO_MODE: "true"
  NEXT_PUBLIC_API_URL: "http://localhost:3001/api/v1"
